# Resolve project root as absolute path from this Justfile's location (works for any clone)
project_root := absolute_path(justfile_directory() / ".." / ".." / ".." / ".." / "..")

download:
  uv run bsf \
  --product resstock \
  --release_year 2024 \
  --weather_file amy2018 \
  --release_version 2 \
  --states RI \
  --file_type "metadata load_curve_hourly" \
  --upgrade_id "0 1 2 3 4 5" \
  --output_directory /data.sb/nrel/resstock \
  --sample 0 # All buildings


test-download:
  cd {{project_root}} && uv run python {{project_root}}/tests/test_resstock_download_to_s3.py \
    --data_path "s3://data.sb/nrel/resstock/" \
    --release res_2024_amy2018_2 \
    --state RI \
    --upgrade_id 00
