utility: nimo
master_tariff_id: 803
start_month: 2025-01
end_month: 2025-12
add_to_drr:
  rate_structure: flat
  charges:
    ev_make_ready:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.00022
        2025-02: 0.00036
        2025-03: 0.00036
        2025-04: 0.00036
        2025-05: 0.00036
        2025-06: 0.00036
        2025-07: 0.00036
        2025-08: 0.00036
        2025-09: 0.00036
        2025-10: 0.00036
        2025-11: 0.00036
        2025-12: 0.00036
    system_benefits_charge:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.007235
        2025-02: 0.007235
        2025-03: 0.007235
        2025-04: 0.007235
        2025-05: 0.007235
        2025-06: 0.007235
        2025-07: 0.003024
        2025-08: 0.003024
        2025-09: 0.003024
        2025-10: 0.003024
        2025-11: 0.003024
        2025-12: 0.003024
    ces_delivery:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.00025
        2025-02: 0.00025
        2025-03: 0.00025
        2025-04: 0.00025
        2025-05: 0.00025
        2025-06: 0.00025
        2025-07: 0.00025
        2025-08: 0.00025
        2025-09: 0.00025
        2025-10: 0.00025
        2025-11: 0.00025
        2025-12: 0.00025
    dlm_surcharge:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.000649
        2025-02: 0.000649
        2025-03: 0.000649
        2025-04: 0.000649
        2025-05: 0.000649
        2025-06: 0.000649
        2025-07: 0.000649
        2025-08: 0.000649
        2025-09: 0.000649
        2025-10: 0.000649
        2025-11: 0.000649
        2025-12: 0.000649
    late_payment_waived_fees:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.00037
        2025-02: 0.00037
        2025-03: 0.00037
        2025-04: 0.00037
        2025-05: 0.00037
        2025-06: 0.00037
    arrears_covid_forgiveness:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.0021
        2025-02: 0.0021
        2025-03: 0.0021
        2025-04: 0.0021
        2025-05: 0.0021
        2025-06: 0.0021
        2025-07: 0.0021
        2025-08: 0.00087
        2025-09: 0.00087
        2025-10: 0.00087
        2025-11: 0.00087
        2025-12: 0.00087
add_to_srr:
  rate_structure: flat
  charges:
    supply_commodity_bundled:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.09303
        2025-02: 0.09041
        2025-03: 0.06353
        2025-04: 0.05105
        2025-05: 0.05458
        2025-06: 0.067
        2025-07: 0.07874
        2025-08: 0.08025
        2025-09: 0.06669
        2025-10: 0.06854
        2025-11: 0.06498
        2025-12: 0.11251
    merchant_function_charge:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: -0.01489
        2025-02: -0.0038840000000000007
        2025-03: 0.021668
        2025-04: 0.016066999999999998
        2025-05: 0.007873999999999999
        2025-06: 0.013252
        2025-07: 0.011478
        2025-08: 0.028161
        2025-09: 0.03061
        2025-10: 0.015403
        2025-11: 0.005130000000000001
        2025-12: -0.025051
    ces_supply_surcharge:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.0057
        2025-02: 0.0057
        2025-03: 0.0057
        2025-04: 0.00741
        2025-05: 0.00741
        2025-06: 0.00741
        2025-07: 0.00741
        2025-08: 0.00741
        2025-09: 0.00741
        2025-10: 0.00741
        2025-11: 0.00741
        2025-12: 0.00741
already_in_drr:
  rate_structure: flat
  charges:
    delivery_charge_adjustment:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.0
        2025-02: 0.0
        2025-03: 0.0
        2025-04: 0.0
        2025-05: 0.0
        2025-06: 0.0
        2025-07: 0.0
        2025-08: 0.0
        2025-09: 0.0
        2025-10: 0.0
        2025-11: 0.0
        2025-12: 0.0
    customer_charge:
      charge_unit: $/month
      monthly_rates:
        2025-01: 17.33
        2025-02: 17.33
        2025-03: 17.33
        2025-04: 17.33
        2025-05: 17.33
        2025-06: 17.33
        2025-07: 17.33
        2025-08: 17.33
        2025-09: 19.0
        2025-10: 19.0
        2025-11: 19.0
        2025-12: 19.0
    core_delivery_rate:
      charge_unit: $/kWh
      monthly_rates:
        2025-01: 0.07576
        2025-02: 0.07576
        2025-03: 0.07576
        2025-04: 0.07576
        2025-05: 0.07576
        2025-06: 0.07576
        2025-07: 0.07576
        2025-08: 0.07576
        2025-09: 0.08889
        2025-10: 0.08889
        2025-11: 0.08889
        2025-12: 0.08889
excluded:
  electricity_supply_charge_adirondack_zone:
    decision: exclude_zonal
  delivery_charge_adjustment_adirondack_zone:
    decision: exclude_zonal
  electric_supply_charge_capital_zone:
    decision: exclude_zonal
  delivery_charge_adjustment_capital_zone:
    decision: exclude_zonal
  electric_supply_charge_frontier_zone:
    decision: exclude_zonal
  delivery_charge_adjustment_frontier_zone:
    decision: exclude_zonal
  electric_supply_charge_genesee_zone:
    decision: exclude_zonal
  delivery_charge_adjustment_genesee_zone:
    decision: exclude_zonal
  electric_supply_charge_utica_zone:
    decision: exclude_zonal
  delivery_charge_adjustment_utica_zone:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_supply_charge:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_supply_charge_1:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_supply_charge_2:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_supply_charge_3:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_supply_charge_4:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_supply_charge_5:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_esrm:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_esrm_1:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_esrm_2:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_esrm_3:
    decision: exclude_zonal
  working_capital_on_purchased_power_costs_factor_esrm_4:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_supply_charge:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_supply_charge_1:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_supply_charge_2:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_supply_charge_3:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_supply_charge_4:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_supply_charge_5:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_esrm:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_esrm_1:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_esrm_2:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_esrm_3:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_esrm_4:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_esrm_5:
    decision: exclude_zonal
  electricity_supply_uncollectible_expense_factor_cess:
    decision: exclude_zonal
  income_eligible_basic_service_credit:
    decision: exclude_eligibility
  revenue_decoupling_mechanism:
    decision: exclude_trueup
  transmission_revenue_adjustment:
    decision: exclude_trueup
  legacy_transition_charge:
    decision: exclude_trueup
  electricity_supply_reconciliation_mechanism:
    decision: exclude_trueup
  electricity_supply_reconciliation_mechanism_1:
    decision: exclude_trueup
  electricity_supply_reconciliation_mechanism_2:
    decision: exclude_trueup
  electricity_supply_reconciliation_mechanism_3:
    decision: exclude_trueup
  electricity_supply_reconciliation_mechanism_4:
    decision: exclude_trueup
  electricity_supply_reconciliation_mechanism_5:
    decision: exclude_trueup
  earnings_adjustment_mechanism:
    decision: exclude_negligible
  minimum:
    decision: exclude_redundant
  net_utility_plant_and_depreciation_expense_reconciliation_mechanism:
    decision: exclude_trueup
  customer_benefit_contribution:
    decision: exclude_percentage
  greenup_charge:
    decision: exclude_eligibility
