# Rate Acuity gas schedule names by utility shortcode (std_name).
# Pass this file to fetch_gas_tariffs_rateacuity.py to fetch all NY gas tariffs.
# Update schedule name values when Rate Acuity names change.
# As of 2026-03-04, most NY gas sales schedules have been moved to "-ON HOLD-" status.
state: NY
cenhud:
  cenhud: "SC 1-RESIDENCE DELIVERY RATE---"
coned:
  coned_nonheating: "-ON HOLD-1-RESIDENTIAL AND RELIGIOUS FIRM SALES SERVICE---"
  coned_sf_heating: "-ON HOLD-3-RESIDENTIAL AND RELIGIOUS - HEATING FIRM SALES SERVICE-Dwelling Units <=4--"
  coned_mf_heating: "-ON HOLD-3-RESIDENTIAL AND RELIGIOUS - HEATING FIRM SALES SERVICE-Dwelling Units > 4--"
kedli:
  kedli_sf_nonheating: "-ON HOLD-1-RESIDENTIAL SERVICE-1A - Non-Heating--"
  kedli_sf_heating: "-ON HOLD-1-RESIDENTIAL SERVICE-1B - Heating--"
  kedli_mf: "-ON HOLD-3-MULTIPLE-DWELLING SERVICE-3A - Non-Heating--"
kedny:
  kedny_sf_nonheating: "-ON HOLD-1A-RESIDENTIAL NON-HEATING SERVICE---"
  kedny_sf_heating: "-ON HOLD-1B-RESIDENTIAL HEATING SERVICE---"
  kedny_mf: "-ON HOLD-3-HEATING AND/OR WATER HEATING SERVICE (MULTI-FAMILY BUILDINGS)---"
nfg:
  nfg: "-ON HOLD-1-RESIDENTIAL-Customers Purchasing Gas Supply from Company--"
nimo:
  nimo: "-ON HOLD-1-RESIDENTIAL DELIVERY SERVICE AND GAS SUPPLY SERVICE OR RESIDENTIAL DELIVERY SERVICE ONLY-Customers Purchasing Gas Supply from Company--"
nyseg:
  nyseg_nonheating: "-ON HOLD-PSC 87, SC 1-RESIDENTIAL SERVICE-Non-Heating--"
  nyseg_heating: "-ON HOLD-PSC 87, SC 1-RESIDENTIAL SERVICE-Heating--"
or:
  or: "-ON HOLD--SERVICE CLASSIFICATION 1-Residential--"
rge:
  rge: "-ON HOLD-1-GENERAL SERVICE-Residential--"
