site_name: rate-design-platform
repo_url: https://github.com/switchbox-data/rate-design-platform
site_url: https://switchbox-data.github.io/rate-design-platform
site_description: A simulation testbed for analyzing the impact of electric rate designs on energy bills and burden for households adopting DERs and all-electric appliances.
site_author: Switchbox
edit_uri: edit/main/docs/
repo_name: switchbox-data/rate-design-platform
copyright: Maintained by <a href="https://switchbox-data.com">switchbox-data</a>.

nav:
  - Home: index.md
  - Modules: modules.md
  - Quarto: docs_tou_hpwh_schedule_basic.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - rate_design_platform
  - quarto-render:
      output_format: gfm

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/switchbox-data/rate-design-platform
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/rate-design-platform

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
