format:
  html:
    mathjax: true
  pdf:
    documentclass: article
    toc: true
  docx:
    toc: true
project:
  output-dir: docs/

execute:
  echo: true
  warning: false
  error: false

bibliography: references.bib
csl: styles/ieee.csl
