# Resolve project root via git (works from any subdirectory in the repo)
project_root := `git rev-parse --show-toplevel`
path_s3_resstock_metadata := "s3://data.sb/nrel/resstock/res_2024_amy2018_2/metadata"
tariff_map_dir_ri := "{{project_root}}/rate_design/ri/hp_rates/data/tariff_map"

# Usage: just map-electric-tariff [electric_utility] [SB_scenario_type] [SB_scenario_year] [upgrade_id] [output_dir]
# Example: just map-electric-tariff Coned default 1 00 ./rate_design/ri/hp_rates/data/tariff_map
map-electric-tariff electric_utility SB_scenario_type SB_scenario_year upgrade_id output_dir:
  uv run python {{project_root}}/utils/electric_tariff_mapper.py \
    --metadata_path "{{path_s3_resstock_metadata}}" \
    --state RI \
    --upgrade_id "{{upgrade_id}}" \
    --electric_utility "{{electric_utility}}" \
    --SB_scenario_type "{{SB_scenario_type}}" \
    --SB_scenario_year "{{SB_scenario_year}}" \
    --output_dir "{{output_dir}}"

# Some useful enumerations:

map-electric-coned-default:
  just map-electric-tariff Coned default 1 00 {{tariff_map_dir_ri}}

map-electric-coned-seasonal:
  just map-electric-tariff Coned seasonal 1 00 {{tariff_map_dir_ri}}

map-celectric-oned-class-specific-seasonal:
  just map-electric-tariff Coned class_specific_seasonal 1 00 {{tariff_map_dir_ri}}

map-electric-national-grid-default:
  just map-electric-tariff "National Grid" default 1 00 {{tariff_map_dir_ri}}

map-electric-national-grid-seasonal:
  just map-electric-tariff "National Grid" seasonal 1 00 {{tariff_map_dir_ri}}

map-electric-national-grid-class-specific-seasonal:
  just map-electric-tariff "National Grid" class_specific_seasonal 1 00 {{tariff_map_dir_ri}}

map-electric-nyseg-default:
  just map-electric-tariff NYSEG default 1 00 {{tariff_map_dir_ri}}

map-electric-nyseg-seasonal:
  just map-electric-tariff NYSEG seasonal 1 00 {{tariff_map_dir_ri}}

map-electric-nyseg-class-specific-seasonal:
  just map-electric-tariff NYSEG class_specific_seasonal 1 00 {{tariff_map_dir_ri}}


# Usage: just map-gas-tariff [electric_utility] [upgrade_id] [output_dir]
# Example: just map-gas-tariff "National Grid" 00 ./rate_design/ri/hp_rates/data/tariff_map
map-gas-tariff electric_utility upgrade_id output_dir:
  uv run python {{project_root}}/utils/gas_tariff_mapper.py \
    --metadata_path "{{path_s3_resstock_metadata}}" \
    --state RI \
    --upgrade_id "{{upgrade_id}}" \
    --electric_utility "{{electric_utility}}" \
    --output_dir "{{output_dir}}"

# Some useful enumerations:

map-gas-coned-default:
  just map-gas-tariff Coned 00 {{tariff_map_dir_ri}}

map-gas-coned-seasonal:
  just map-gas-tariff Coned 00 {{tariff_map_dir_ri}}

map-gas-coned-class-specific-seasonal:
  just map-gas-tariff Coned 00 {{tariff_map_dir_ri}}

map-gas-national-grid-default:
  just map-gas-tariff "National Grid" 00 {{tariff_map_dir_ri}}

map-gas-national-grid-seasonal:
  just map-gas-tariff "National Grid" 00 {{tariff_map_dir_ri}}

map-gas-national-grid-class-specific-seasonal:
  just map-gas-tariff "National Grid" 00 {{tariff_map_dir_ri}}

map-gas-nyseg-default:
  just map-gas-tariff NYSEG 00 {{tariff_map_dir_ri}}

map-gas-nyseg-seasonal:
  just map-gas-tariff NYSEG 00 {{tariff_map_dir_ri}}

map-gas-nyseg-class-specific-seasonal:
  just map-gas-tariff NYSEG 00 {{tariff_map_dir_ri}}
