utility: coned
load_method: resstock
delivery_revenue_requirement_from_rate_case: 3116197000.0
delivery_revenue_requirement_topups: 171585738.4
supply_revenue_requirement_topups: 1606892846.79
total_delivery_revenue_requirement: 3287782738.4
total_delivery_and_supply_revenue_requirement: 4894675585.19
total_residential_kwh: 16052971067.52
eia_total_residential_kwh: 13643968512.0
eia_year: 2024
delivery_top_ups:
  dlm_surcharge:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 27820672.4
  ev_make_ready:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 12000410.5
  arrears_covid_forgiveness:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 19263565.28
  ces_delivery:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 4639308.64
  system_benefits_charge:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 90203513.41
  ny_state_surcharge_18_a:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 0.0
  vder_der_cost_recovery:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 17658268.17
supply_top_ups:
  merchant_function_charge:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 71151167.24
  supply_commodity_bundled:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 1469414557.64
  ces_supply_surcharge:
    charge_unit: $/kWh
    budget_method: resstock
    total_budget: 66327121.91
resstock_monthly_kwh:
  1: 1683932716.34
  2: 1253860980.75
  3: 1345179494.44
  4: 1090404417.17
  5: 1125896192.27
  6: 1266278513.55
  7: 1650718806.73
  8: 1701621876.32
  9: 1262686937.16
  10: 1089000434.13
  11: 1196233425.06
  12: 1387157273.6
resstock_scale_factor: 0.786806
