utility: nimo
delivery_revenue_requirement_from_rate_case: 1314441124.0
delivery_revenue_requirement_topups: 96176365.89
supply_revenue_requirement_topups: 1066261846.59
total_delivery_revenue_requirement: 1410617489.89
total_delivery_and_supply_revenue_requirement: 2476879336.48
total_residential_kwh: 11833894912.0
eia_year: 2024
delivery_top_ups:
  ev_make_ready:
    charge_unit: $/kWh
    avg_monthly_rate: 0.0003481096
    total_budget: 4119492.29
  system_benefits_charge:
    charge_unit: $/kWh
    avg_monthly_rate: 0.0051121945
    total_budget: 60497172.73
  ces_delivery:
    charge_unit: $/kWh
    avg_monthly_rate: 0.00025
    total_budget: 2958473.73
  dlm_surcharge:
    charge_unit: $/kWh
    avg_monthly_rate: 0.000649
    total_budget: 7680197.8
  late_payment_waived_fees:
    charge_unit: $/kWh
    avg_monthly_rate: 0.0001834795
    total_budget: 2171276.55
  arrears_covid_forgiveness:
    charge_unit: $/kWh
    avg_monthly_rate: 0.001584411
    total_budget: 18749752.79
supply_top_ups:
  supply_commodity_bundled:
    charge_unit: $/kWh
    avg_monthly_rate: 0.0742730411
    total_budget: 878939363.12
  merchant_function_charge:
    charge_unit: $/kWh
    avg_monthly_rate: 0.0088409616
    total_budget: 104623011.01
  ces_supply_surcharge:
    charge_unit: $/kWh
    avg_monthly_rate: 0.0069883562
    total_budget: 82699472.46
