utility: or
group_col: has_hp
source_run_dir: s3://data.sb/switchbox/cairo/outputs/hp_rates/ny/or/ny_20260323a_r1-16/20260323_200011_ny_or_run1_up00_precalc__default
total_delivery_revenue_requirement: 263364257.0
total_delivery_and_supply_revenue_requirement: 431562114.21
subclass_revenue_requirements:
  delivery:
    percustomer:
      non-hp: 254976490.86444885
      hp: 8387766.13555118
  supply:
    passthrough: &id001
      non-hp: 158986971.95407706
      hp: 9210885.255922925
    percustomer: *id001
