state: MD
upgrade_id: '02'
input_release: res_2024_amy2018_2_sb
output_release: res_2024_amy2018_2_sb_ach
climate_zone: A_4
elapsed_seconds: 226.6
n_buildings_total: 9996
group_counts:
  Heat Pump: 9996
  Heat Pump__approximated: 265
  Electric Resistance: 0
  Natural Gas: 0
  Delivered Fuels: 0
  unclassified: 0
regressions:
  Heat Pump__elec_heating:
    slope: !!python/object/apply:numpy._core.multiarray.scalar
      - &id001 !!python/object/apply:numpy.dtype
        args:
          - f8
          - false
          - true
        state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
      - !!binary |
        sd6oFabvtT8=
    intercept: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        HVVNEHUf8z8=
    r_squared: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        nzws1Jrm0T8=
    n: 9731
  Heat Pump__elec_cooling:
    slope: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        pdqn4zEDlT8=
    intercept: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        kKM5svJL6j8=
    r_squared: !!python/object/apply:numpy._core.multiarray.scalar
      - *id001
      - !!binary |
        I9v5fmq8xD8=
    n: 9731
correction_fractions:
  Heat Pump__elec_cooling:
    mean: 0.159136
    median: 0.119789
    std: 0.190927
    min: -0.5
    max: 1.0
  Heat Pump__elec_heating:
    mean: 0.2795
    median: 0.223434
    std: 0.326761
    min: -0.5
    max: 1.0
