state: ri
utility: rie
year: 2025
solar_pv_compensation: net_metering
process_workers: 8
resstock:
  base: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb
  upgrade_precalc: "00"
  upgrade_calibrated: "02"
marginal_costs:
  dist_and_sub_tx: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
  bulk_tx: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
  supply_energy: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/data.parquet
  supply_capacity: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/data.parquet
revenue_requirement:
  precalc: rev_requirement/rie_rate_case_test_year.yaml
  calibrated: rev_requirement/rie_large_number_rate_case_test_year.yaml
residual_allocation:
  delivery: percustomer
  supply: passthrough
scenario: default
