runs:
  ri_rie_default_precalc_delivery:
    run_name: ri_rie_default_precalc_delivery
    state: RI
    utility: rie
    run_type: precalc
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=00/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=00/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_default.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u00.csv
    path_tariffs_electric:
      all: tariffs/electric/rie_default.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_default_precalc_delivery
    utility_revenue_requirement: rev_requirement/rie_rate_case_test_year.yaml
    run_includes_supply: false
    run_includes_subclasses: false
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/zero.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/zero.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
  ri_rie_default_precalc_supply:
    run_name: ri_rie_default_precalc_supply
    state: RI
    utility: rie
    run_type: precalc
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=00/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=00/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_default_supply.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u00.csv
    path_tariffs_electric:
      all: tariffs/electric/rie_default_supply.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_default_precalc_supply
    utility_revenue_requirement: rev_requirement/rie_rate_case_test_year.yaml
    run_includes_supply: true
    run_includes_subclasses: false
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/data.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/data.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
  ri_rie_default_calibrated_delivery:
    run_name: ri_rie_default_calibrated_delivery
    state: RI
    utility: rie
    run_type: default
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=02/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=02/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_default_calibrated.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u02.csv
    path_tariffs_electric:
      all: tariffs/electric/rie_default_calibrated.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_default_calibrated_delivery
    utility_revenue_requirement: rev_requirement/rie_large_number_rate_case_test_year.yaml
    run_includes_supply: false
    run_includes_subclasses: false
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/zero.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/zero.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
  ri_rie_default_calibrated_supply:
    run_name: ri_rie_default_calibrated_supply
    state: RI
    utility: rie
    run_type: default
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=02/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=02/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_default_supply_calibrated.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u02.csv
    path_tariffs_electric:
      all: tariffs/electric/rie_default_supply_calibrated.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_default_calibrated_supply
    utility_revenue_requirement: rev_requirement/rie_large_number_rate_case_test_year.yaml
    run_includes_supply: true
    run_includes_subclasses: false
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/data.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/data.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
  ri_rie_hp_seasonal_percustomer_passthrough_precalc_delivery:
    run_name: ri_rie_hp_seasonal_percustomer_passthrough_precalc_delivery
    state: RI
    utility: rie
    run_type: precalc
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=00/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=00/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_hp_seasonal_vs_non-hp_base.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u00.csv
    path_tariffs_electric:
      hp: tariffs/electric/rie_hp_seasonal_percustomer_percustomer.json
      non-hp: tariffs/electric/rie_non-hp_base_percustomer_percustomer.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_hp_seasonal_percustomer_passthrough_precalc_delivery
    utility_revenue_requirement: rev_requirement/rie_hp_vs_non-hp.yaml
    run_includes_supply: false
    run_includes_subclasses: true
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/zero.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/zero.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
    residual_allocation_delivery: percustomer
    residual_allocation_supply: percustomer
    subclass_config:
      group_col: has_hp
      selectors:
        hp: 'true'
        non-hp: 'false'
  ri_rie_hp_seasonal_percustomer_passthrough_precalc_supply:
    run_name: ri_rie_hp_seasonal_percustomer_passthrough_precalc_supply
    state: RI
    utility: rie
    run_type: precalc
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=00/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=00/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_hp_seasonal_vs_non-hp_base_supply.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u00.csv
    path_tariffs_electric:
      hp: tariffs/electric/rie_hp_seasonal_percustomer_percustomer_supply.json
      non-hp: tariffs/electric/rie_non-hp_base_percustomer_percustomer_supply.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_hp_seasonal_percustomer_passthrough_precalc_supply
    utility_revenue_requirement: rev_requirement/rie_hp_vs_non-hp.yaml
    run_includes_supply: true
    run_includes_subclasses: true
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/data.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/data.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
    residual_allocation_delivery: percustomer
    residual_allocation_supply: percustomer
    subclass_config:
      group_col: has_hp
      selectors:
        hp: 'true'
        non-hp: 'false'
  ri_rie_hp_seasonal_percustomer_passthrough_calibrated_delivery:
    run_name: ri_rie_hp_seasonal_percustomer_passthrough_calibrated_delivery
    state: RI
    utility: rie
    run_type: default
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=02/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=02/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_hp_seasonal_vs_non-hp_base_calibrated.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u02.csv
    path_tariffs_electric:
      all: tariffs/electric/rie_hp_seasonal_percustomer_percustomer_calibrated.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_hp_seasonal_percustomer_passthrough_calibrated_delivery
    utility_revenue_requirement: rev_requirement/rie_large_number_rate_case_test_year.yaml
    run_includes_supply: false
    run_includes_subclasses: false
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/zero.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/zero.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
    residual_allocation_delivery: percustomer
    residual_allocation_supply: percustomer
  ri_rie_hp_seasonal_percustomer_passthrough_calibrated_supply:
    run_name: ri_rie_hp_seasonal_percustomer_passthrough_calibrated_supply
    state: RI
    utility: rie
    run_type: default
    path_resstock_metadata: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata/state=RI/upgrade=02/metadata-sb.parquet
    path_resstock_loads: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/load_curve_hourly/state=RI/upgrade=02/
    path_utility_assignment: /ebs/data/nrel/resstock/res_2024_amy2018_2_sb/metadata_utility/state=RI/utility_assignment.parquet
    path_tariff_maps_electric: tariff_maps/electric/rie_hp_seasonal_vs_non-hp_base_supply_calibrated.csv
    path_tariff_maps_gas: tariff_maps/gas/rie_u02.csv
    path_tariffs_electric:
      all: tariffs/electric/rie_hp_seasonal_percustomer_percustomer_supply_calibrated.json
    path_tariffs_gas: tariffs/gas
    path_outputs: /data.sb/switchbox/cairo/outputs/hp_rates/ri/rie/ri_20260803_b/ri_rie_hp_seasonal_percustomer_passthrough_calibrated_supply
    utility_revenue_requirement: rev_requirement/rie_large_number_rate_case_test_year.yaml
    run_includes_supply: true
    run_includes_subclasses: false
    path_dist_and_sub_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/dist_and_sub_tx/utility=rie/year=2025/data.parquet
    path_bulk_tx_mc: s3://data.sb/switchbox/marginal_costs/ri/bulk_tx/utility=rie/year=2025/data.parquet
    path_supply_energy_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/energy/utility=rie/year=2025/data.parquet
    path_supply_capacity_mc: s3://data.sb/switchbox/marginal_costs/ri/supply/capacity/utility=rie/year=2025/data.parquet
    path_electric_utility_stats: s3://data.sb/eia/861/electric_utility_stats/year=2024/state=RI/data.parquet
    solar_pv_compensation: net_metering
    year_run: 2025
    year_dollar_conversion: 2025
    process_workers: 8
    elasticity: 0.0
    residual_allocation_delivery: percustomer
    residual_allocation_supply: percustomer
subclass_config:
  group_col: has_hp
  selectors:
    hp: 'true'
    non-hp: 'false'
