name: Deploy Documentation

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Install dev dependencies
        run: uv sync --group dev --group docs

      - name: Build documentation
        run: |
          # Ensure data directory exists and has required files
          ls -la data/
          # Force Quarto to regenerate all files
          find docs -name "*.qmd" -exec touch {} \;
          # Clean any existing generated files
          rm -rf docs/*_files/
          uv run mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
